# Generated by Django 2.2 on 2021-09-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_year', to='T_app.Home'),
        ),
    ]
