# Generated by Django 2.2 on 2021-09-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('T_app', '0002_auto_20210909_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year',
            new_name='ReportY',
        ),
    ]
